language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - travis_retry composer self-update
  - curl http://cs.sensiolabs.org/get/php-cs-fixer.phar -o php-cs-fixer.phar
  - if [[ "$TRAVIS_PHP_VERSION" == *5.6* ]]; then travis_retry composer require "satooshi/php-coveralls:~0.6.1" "symfony/yaml=~2.0" --prefer-source --no-interaction --dev; else travis_retry composer install --prefer-source --no-interaction; fi

script:
  - output=$(php -n php-cs-fixer.phar fix -v --dry-run src); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;
  - phpunit -c phpunit.xml --coverage-text

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == *5.6* ]]; then php vendor/bin/coveralls -v; fi

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true
